# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('menu_include', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=36)),
                ('api_key', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='slideshow_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=15)),
                ('image_include', models.BooleanField(default=False)),
                ('alt', models.CharField(max_length=100)),
                ('sort', models.IntegerField()),
            ],
        ),
    ]
