# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='url',
        ),
        migrations.AddField(
            model_name='schedule',
            name='iframeCode',
            field=models.CharField(default='not set', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='include',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='information',
            name='img',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='slideshow_images',
            name='fileName',
            field=models.FileField(max_length=15, upload_to=b''),
        ),
    ]
